apiVersion: v1
kind: Service
metadata:
  name: safemigrate-postgres
  namespace: safemigrate
  labels:
    app: safemigrate-postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: safemigrate-postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: safemigrate-postgres
  namespace: safemigrate
  labels:
    app: safemigrate-postgres
spec:
  serviceName: "safemigrate-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: safemigrate-postgres
  template:
    metadata:
      labels:
        app: safemigrate-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          command:
            - "postgres"
            - "-c"
            - "wal_level=logical"
            - "-c"
            - "max_replication_slots=10"
            - "-c"
            - "max_wal_senders=10"
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: safemigrate-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: safemigrate-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: safemigrate-config
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - safemigrate_test
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
