apiVersion: v1
kind: Secret
metadata:
  name: safemigrate-secrets
  namespace: safemigrate
  labels:
    app.kubernetes.io/name: safemigrate
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
